In [195]:
import pandas as pd
import csv
import matplotlib.pyplot as plt
import numpy as np

import random

from sklearn.neighbors import LocalOutlierFactor
from sklearn.ensemble import IsolationForest
from sklearn.covariance import EllipticEnvelope
from sklearn.svm import SVC

from sklearn import svm

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

#read labeld data for user i


results_df = pd.DataFrame(columns=["id","label"])

In [204]:
testUser=11
#reading the data
dataset = pd.read_csv("partial_labels.csv")
#for all
x,segments=dataset.axes
array=dataset.values
#z=np.reshape(array[testUser,1:],-1)
#z=z.astype('int')
#Y_train=z[0:50]
#Y_test=z

#read instructions
fileName =array[testUser,0]
path_read = "../Detecting-Cyber-Attacks-Kaggle-Callenge/data/FraudedRawData/User0"
all_instructions = pd.read_csv(path_read, sep=" ", header=None)
arr=np.reshape(instructions.values,(150,100))

In [205]:

uniqe=set()
strange=[]
index=[]
z=0
x_train=[]

index=0
wordsCount={}
countbackwrd= set()
len_countbackwrd=[]
word_lenght=[]
count = 0
mean_len=0
uniqcheck=set()
count_vec_all=[]
count_vec_usr=[]
vectorizer = TfidfVectorizer(min_df=0.4,ngram_range=(1,2))
from __future__ import division
cout_len=0
for i in range(150):
    Str=' '.join((arr[i,:]))
    if(i<50):
        count_vec_usr.append(' '.join(arr[i,:]))
        count_vec_all.append(' '.join(arr[i,:]))
    else:
        count_vec_all.append(' '.join(arr[i,:]))
vectorizer.fit_transform(count_vec_all)
X_all = vectorizer.transform(count_vec_all)
X_all=X_all.toarray()
X_usr = vectorizer.transform(count_vec_usr)
X_usr=X_usr.toarray()


for i in range(50):
    for j in range(100):
        uniqe.add(arr[i][j])
    x_train.append([random.randint(0, 2)])

    
count=0
for i in range(50,150):
    for j in range(100):
        uniqcheck.add(arr[i][j])
        if (arr[i][j] not in uniqe):
            count = count + 1
       
    strange.append([count])
    uniqcheck.clear()
    count = 0

In [206]:

#train module
x_test=np.concatenate((x_train,strange))
x_test=np.c_[X_all,x_test]
x_train=np.c_[X_usr,x_train]
clf= LocalOutlierFactor(n_neighbors=25,contamination=0.1, novelty=True)
clf.fit(x_train)
t=clf.predict(x_test)
t[t == 1] = 0
t[t == -1] = 1

curr_user_results = t[50:150]
curr_user_results_df = pd.DataFrame(columns=["id","label"])

start_rows = 5000
till_rows = 5100

for i in range(curr_user_results.size):
    curr_user_results_df.loc[i] = ["User{}_{}-{}".format(testUser,start_rows,till_rows),curr_user_results[i]]
    start_rows = start_rows + 100
    till_rows = till_rows + 100
results_df = results_df.append(curr_user_results_df)


#plot data
#c=0
#for i in range(len(t)):
#    if(t[i]==1):
#        if(Y_test[i]==0):
#            plt.plot(i,Y_test[i], 'go')
#        else:
#            plt.plot(i, Y_test[i], 'ro')
            #print(i)
#            c = c + 1
#    else:
#        if(Y_test[i]==1):
#            plt.plot(i,Y_test[i], 'go')
#        else:
#            plt.plot(i, Y_test[i], 'ro')
            #print(i)
#            c=c+1
#print(c)

#plt.show()

In [207]:
results_df

                    id label
0     User10_5000-5100     1
1     User10_5100-5200     0
2     User10_5200-5300     0
3     User10_5300-5400     1
4     User10_5400-5500     0
5     User10_5500-5600     0
6     User10_5600-5700     1
7     User10_5700-5800     0
8     User10_5800-5900     0
9     User10_5900-6000     0
10    User10_6000-6100     0
11    User10_6100-6200     0
12    User10_6200-6300     0
13    User10_6300-6400     0
14    User10_6400-6500     0
15    User10_6500-6600     0
16    User10_6600-6700     0
17    User10_6700-6800     0
18    User10_6800-6900     0
19    User10_6900-7000     0
20    User10_7000-7100     0
21    User10_7100-7200     0
22    User10_7200-7300     0
23    User10_7300-7400     0
24    User10_7400-7500     0
25    User10_7500-7600     0
26    User10_7600-7700     0
27    User10_7700-7800     0
28    User10_7800-7900     0
29    User10_7900-8000     0
..                 ...   ...
70  User11_12000-12100     1
71  User11_12100-12200     1
72  User11_12200-12300     1
73  User11_12300-12400     1
74  User11_12400-12500     1
75  User11_12500-12600     1
76  User11_12600-12700     0
77  User11_12700-12800     1
78  User11_12800-12900     0
79  User11_12900-13000     1
80  User11_13000-13100     0
81  User11_13100-13200     0
82  User11_13200-13300     1
83  User11_13300-13400     0
84  User11_13400-13500     1
85  User11_13500-13600     0
86  User11_13600-13700     0
87  User11_13700-13800     0
88  User11_13800-13900     1
89  User11_13900-14000     1
90  User11_14000-14100     0
91  User11_14100-14200     0
92  User11_14200-14300     0
93  User11_14300-14400     0
94  User11_14400-14500     1
95  User11_14500-14600     1
96  User11_14600-14700     1
97  User11_14700-14800     1
98  User11_14800-14900     1
99  User11_14900-15000     1

[200 rows x 2 columns]

In [ ]:

fname = "out/submission_results_{}.csv".format(date.today())
results_df.to_csv(fname, index=False)
os.system('kaggle competitions submit -c detectingcyberattackscallenge -f "{0}" -m "{1}"'.format(fname, "Submitting results to kaggle"))